# Generated by Django 6.0.4 on 2026-04-30 13:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modeles', to='parc_auto.marque')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[A-Z]$', 'Seulement une lettre majuscule de A à Z')])),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('kms', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicules', to='parc_auto.modele')),
            ],
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_intervention', models.DateField()),
                ('description', models.TextField()),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entretiens', to='parc_auto.vehicule')),
            ],
        ),
    ]
