# Generated by Django 6.0.4 on 2026-04-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc_auto', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vehicule',
            constraint=models.UniqueConstraint(fields=('nom', 'modele'), name='unique_nom_par_modele'),
        ),
    ]
